###########################################################
### 欢迎使用 Beautiful Jekyll!
### 此配置文件用于影响您整个网站的设置。当您第一次
### 设置您的网站时，应逐一查看这些设置并进行编辑，但在
### 初始设置之后，您无需经常回到此文件。
###########################################################

############################
# --- 必需选项 --- #
############################

# 网站名称
title: My website

# 显示在页脚的您的名字
author: Some Person

###############################################
# --- 导航栏中的链接列表 --- #
###############################################

navbar-links:
  关于我: "aboutme"
  资源:
    - Beautiful Jekyll: "https://694426204.github.io/Navigation-Website/"
    - 学习 markdown: "https://www.markdowntutorial.com/"
  作者主页: "https://deanattali.com"

################
# --- 图标 --- #
################

# 导航栏中显示的图片 - 方形图片效果最佳
# 如果不希望导航栏中显示图片，请移除此参数
avatar: "/assets/img/avatar-icon.png"

# 默认情况下，图像被裁切成圆形。您可以通过设置 'round-avatar: false' 来禁用此行为。
round-avatar: true

# 如果您希望左上角显示图片 logo 而不是网站标题，
# 请指定以下参数
#title-img: /path/to/image


#####################################
# --- 页脚社交媒体链接 --- #
#####################################

# 选择要在页脚中显示的社交网络链接。
# 您可以通过更改此处的顺序来更改它们在页面上的显示顺序。
# 取消注释要显示的链接，并为每个链接添加您的信息。
social-network-links:
  email: "someone@example.com"
  rss: true  # 如果不希望底部显示 RSS 链接，请移除此行
  facebook: deanattali
  github: daattali
  twitter: daattali
  patreon: DeanAttali
  youtube: "@daattali"
  whatsapp: 15551212
#  medium: yourname
#  reddit: yourname 或 r/yoursubreddit
#  linkedin: daattali
#  xing: yourname
#  stackoverflow: "3943160/daattali"
#  snapchat: deanat78
#  instagram: deanat78
#  spotify: yourname
#  telephone: +14159998888
#  steam: deanat78
#  twitch: yourname
#  yelp: yourname
#  telegram: yourname
#  calendly: yourname
#  mastodon: instance.url/@username
#  bluesky: yourname
#  ORCID: 您的 ORCID ID
#  google-scholar: 您的 google scholar
#  discord: "邀请码" 或 "users/userid" 或 "invite/邀请码"
#  kaggle: yourname
#  hackerrank: yourname
#  gitlab: yourname
#  itchio: yourname
#  untappd: yourname
#  strava: 您的用户ID

# 如果您希望网站生成 RSS 源，请提供描述
# 源的 URL 将是 https://<your_website>/feed.xml
rss-description: 这个网站是我很棒的虚拟证明

###########################
# --- 常规选项 --- #
###########################

# 选择在文章中显示哪些社交网络分享链接
share-links-active:
  twitter: true
  facebook: true
  linkedin: true
  vk: false
  reddit: false

# 如何在页脚中显示指向您网站的链接
# 如果不希望页脚中有链接，请移除此项
url-pretty: "MyWebsite.com"

# 在每个页面的标题中添加网站标题
title-on-all-pages: true

# 摘要词数 - 将订阅源页面上每篇文章的摘要截断为指定的单词数
excerpt_length: 50

# 是否在订阅源页面中为每篇博客文章显示摘要
feed_show_excerpt: true

# 是否在订阅源页面的每篇文章预览下方显示标签列表
feed_show_tags: true

# 在导航栏中添加搜索按钮
post_search: true

# 在页脚中添加一个按钮来编辑当前页面。仅当您的网站托管在 GitHub 上时有效
edit_page_button: true

# 允许子菜单项（二级导航菜单项）长于顶级菜单
# 如果关闭此设置，长的子菜单单词可能会被截断
# 请参阅 https://github.com/daattali/beautiful-jekyll/issues/765 了解此设置可以解决的问题
navbar-var-length: false

# 与您的网站关联的关键词，用于 SEO 目的
#keywords: "我的,关键词,列表"

######################################
# --- 颜色 / 背景图片 --- #
######################################

# 个性化您网站中的颜色。颜色值可以是任何有效的 CSS 颜色

page-col: "#FFFFFF"
text-col: "#404040"
link-col: "#008AFF"
hover-col: "#0085A1"
navbar-col: "#EAEAEA"
navbar-text-col: "#404040"
navbar-border-col: "#DDDDDD"
footer-col: "#EAEAEA"
footer-text-col: "#777777"
footer-link-col: "#404040"
footer-hover-col: "#0085A1"

# 或者，导航栏、页脚和页面背景可以设置为图片
# 而不是颜色

#navbar-img: "/assets/img/bgimage.png"
#footer-img: "/assets/img/bgimage.png"
#page-img: "/assets/img/bgimage.png"

# 建议移动浏览器用作浏览器主题的颜色。仅少数移动浏览器支持。
#mobile-theme-col: "#0085A1"

# 对于任何额外的视觉自定义，您可以在网站的每个页面中包含额外的 CSS 文件。在此处列出任何自定义 CSS 文件
#site-css:
#  - "/assets/css/custom-styles.css"

# 如果您有应该包含在每个页面中的通用 JavaScript 文件，请在此处列出
#site-js:
#  - "/assets/js/custom-script.js"

#################################
# --- 网站数据分析部分 --- #
#################################

# 填写您的 Google Analytics 标签 ID（或"衡量 ID"）以跟踪您的网站使用情况
#gtag: "G-XXXXXXXXXX"

# 填写您的 Cloudflare Analytics 信标令牌以使用 Cloudflare Analytics 跟踪您的网站
#cloudflare_analytics: ""

# Google Tag Manager ID
#gtm: ""

# Matomo（又名 Piwik）网站统计
# 取消注释以下部分以启用 Matomo。opt-out 参数控制
# 是否允许用户选择退出跟踪。
#matomo:
#  site_id: "9"
#  uri: "demo.wiki.pro"
#  opt-out: true

# Google Universal Analytics ID -- 已弃用
# 截至 2023 年 7 月，Google 不再支持此功能！如果您仍在使用 `google_analytics`，
# 则应改用上面的 `gtag` 字段。
#google_analytics: "UA-XXXXXXXX-X"

####################
# --- 评论 --- #
####################

# 要使用 Disqus 评论，请注册 https://disqus.com 并填写您的 Disqus 简称（不是用户 ID）
#disqus: ""

# 要使用 Facebook 评论，请创建一个 Facebook 应用并填写 Facebook 应用 ID
#fb_comment_id: ""

# 要使用 CommentBox，请在 https://commentbox.io 注册项目 ID
#commentbox: "" # 项目 ID，例如 "5694267682979840-proj"

# 要使用 Utterances 评论：(0) 取消注释以下部分，(1) 填写
# "repository"（确保仓库是公开的），(2) 在您的仓库中启用 Issues，
# (3) 在您的仓库中安装 Utterances 应用 https://github.com/apps/utterances
# 有关以下参数的更多详细信息，请参阅 https://utteranc.es/
#utterances:
#  repository: # GitHub 用户名/仓库 例如 "daattali/beautiful-jekyll"
#  issue-term: title   # 博客文章和 GitHub Issues 之间的映射
#  theme: github-light # Utterances 主题
#  label: blog-comments # 将分配给 Utterances 创建的 GitHub Issues 的标签

# 要使用 Staticman 评论，请取消注释以下部分。如果您不使用 reCaptcha 进行垃圾邮件保护，
# 可以保留 reCaptcha 部分的注释。
# 使用 Staticman 需要高级知识，请查阅
# https://github.com/eduardoboucas/staticman/ 和 https://staticman.net/ 了解更多
# 说明。对于 staticman 的任何支持，请将问题直接指向 staticman，
# 而不是指向 BeautifulJekyll。
#staticman:
#  repository : # GitHub 用户名/仓库 例如 "daattali/beautiful-jekyll"
#  branch     : master # 如果您不使用 `master` 分支，那么您还需要更新 `staticman.yml` 中的 `branch` 参数
#  endpoint   : # 您的部署 URL，带尾部斜杠 例如 "https://<your-api>/v3/entry/github/"
#  reCaptcha:   # （可选，也在 `staticman.yml` 中设置这些参数）
#    siteKey  : # 您需要在 Google 上申请站点密钥
#    secret   : # 访问 https://<your-own-api>/v3/encrypt/<your-site-secret> 来加密您的密码

# 要使用 giscus 评论：
# (0) 取消注释以下 giscus 部分，(1) 在您的 GitHub 仓库中启用 Discussions，
# (2) 在您的仓库中安装 giscus 应用（详情请参阅 https://giscus.app），
# (3) 填写以下*所有*参数
# 有关 giscus 和以下每个参数的更多详细信息，请参阅 https://giscus.app
#giscus:
#  hostname: giscus.app # 如果您自托管，请替换为您的 giscus 实例主机名
#  repository: # GitHub 用户名/仓库 例如 "daattali/beautiful-jekyll"
#  repository-id: # 您的仓库 ID，从 https://giscus.app 获取此信息
#  category: 公告 # 您的 GitHub Discussion 帖子的类别名称
#  category-id: # 您的类别的 ID，从 https://giscus.app 获取
#  mapping: pathname
#  reactions-enabled: 1
#  emit-metadata: 0
#  theme: light

################
# --- 其他 --- #
################

# 显示文章日期的 Ruby 日期格式
date_format: "%Y年%-m月%-d日"

# Facebook 应用 ID
#fb_app_id: ""

#################################################################################
# --- 您不需要触摸下面的任何内容（但如果您愿意，也可以） --- #
#################################################################################

# 输出选项（更多信息请参阅 Jekyll 网站）
timezone: "Asia/Shanghai"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM

# 默认 YAML 值（更多信息请参阅 Jekyll 网站）
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # 为所有博客文章添加评论
      social-share: true # 为所有博客文章添加社交媒体分享按钮
  -
    scope:
      path: "" # 任何不是文章的文件默认使用 "page" 布局
    values:
      layout: "page"

# 从生产站点中排除这些文件
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/

plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Beautiful Jekyll / Dean Attali
# 2fc73a3a967e97599c9763d05e564189
